name: cypress-test
on: [push]
jobs: 
  run-cypress: 
    runs-on: ubuntu-20.04 
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./